language: node_js
node_js: 12
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - next

env:
  - BROWSER=chromium

before_script:
  - NODE_ENV=development yarn build:bundles

jobs:
  include:
    - stage: tests
      name: Unit Tests
      script:
        - yarn jest src

    - name: '[Chrome] Functional Tests'
      script:
        - BROWSER=chromium yarn jest tests/functional

    - name: '[Firefox] Functional Tests'
      script:
        - BROWSER=firefox travis_retry yarn jest tests/functional
