dist: bionic
language: node_js
node_js: 12
cache:
  yarn: true
  directories:
    - node_modules
    - docs/.cache
    - docs/node_modules
    - docs/public

jobs:
  include:
    - stage: Functional Tests
      name: 'Chrome'
      script: PUPPETEER_BROWSER=chromium travis_retry yarn test:functional

    #- name: '[Firefox] Functional Tests'
    #  script: PUPPETEER_BROWSER=firefox travis_retry yarn jest tests/functional
