language: node_js
dist: trusty
node_js: 12
script:
  - yarn test:ci
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - next
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
  # Enable user namespace cloning
  - 'sysctl kernel.unprivileged_userns_clone=1'
  # Launch XVFB
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
