language: node_js
node_js: 12
script:
  - NODE_ENV=development yarn build:bundles
  - BROWSER=chromium yarn test:ci
  - BROWSER=firefox yarn test:ci tests/functional
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - next
