language: node_js
node_js: 12
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - next

before_script:
  - NODE_ENV=development yarn build:bundles

jobs:
  include:
    - stage: Code Check
      name: Flow Type
      script: yarn flow

    - name: ESLint
      script: yarn eslint

    - stage: tests
      name: Unit Tests
      script: yarn jest --coverage src

    - name: '[Chrome] Functional Tests'
      script: PUPPETEER_BROWSER=chromium travis_retry yarn jest tests/functional
    #- name: '[Firefox] Functional Tests'
    #  script: PUPPETEER_BROWSER=firefox travis_retry yarn jest tests/functional
