name: Functional Tests
on: [push, pull_request]
env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  PUPPETEER_EXEC_PATH: google-chrome-stable

jobs:
  functional-chromium:
    name: Chromium Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - uses: ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb
        with:
          args: yarn test:functional
        env:
          PUPPETEER_BROWSER: chromium
