name: Release Floating UI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/typescript
      - uses: ./.github/actions/unit
      - uses: ./.github/actions/functional

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm run build:typescript
      - run: npm run lint-packages
      - run: npx changeset version
      - run: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
